---
name: 🐛 Bug Report
about: Report a bug you've discovered
labels: bug
---

<!--
⚠️ IMPORTANT: Before submitting, please:
1. Search existing issues to avoid creating duplicates
2. Consider starring the repository to support the project and increase its reach
-->


## 🐞 Describe the Bug

<!-- A clear and concise description of what the bug is. -->

## 🔍 Steps to Reproduce

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

## 🎯 Expected Behavior

<!-- A clear and concise description of what you expected to happen. -->

## 📱 Screenshots/Videos

<!-- If applicable, add screenshots or screen recordings to help explain your problem. -->

## 🌍 Environment

- Device: [e.g., iPhone 12, Windows 10 PC]
- Browser: [e.g., Chrome 98, Safari 15]
- OS: [e.g., iOS 15.2, Windows 10]

## 📋 Additional Context

<!-- Add any other context about the problem here. -->

## 🛠️ Possible Solution

<!-- If you have suggestions for a fix, please describe them here. -->
